# Generated by Django 5.2.7 on 2025-10-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race50', '0002_session_lap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lap',
            old_name='lap_no',
            new_name='lap',
        ),
        migrations.RenameField(
            model_name='lap',
            old_name='lap_time_ms',
            new_name='total_ms',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='track_name',
            new_name='track',
        ),
        migrations.AlterUniqueTogether(
            name='lap',
            unique_together={('session', 'lap')},
        ),
        migrations.AddField(
            model_name='lap',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='avg_lap_ms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='best_lap_ms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='best_lap_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='consistency_percent',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='laps_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='tbl_ms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='worst_lap_ms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='lap',
            index=models.Index(fields=['session', 'lap'], name='race50_lap_session_737f26_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'date'], name='race50_sess_user_id_cbf368_idx'),
        ),
        migrations.RemoveField(
            model_name='lap',
            name='valid',
        ),
    ]
